### PR TITLE
Package upgrade. Last link. Total count. PageSize. Bug fix.

### PR DESCRIPTION
**Pull request by ismarslomic**
* Added total count of resources for `query` by adding `X-Total-Count header`
* Added `last` relation in Link Header for showing URL to last page with results
* Added `pageSize` as query string parameter in order to set page size for pagination in the URL itself
* Fixed bug when returning Location URL for `PATCH`, model._id was duplicated
* Changed status code to `201 CREATED` for successful `POST` requests
* Updated runtime and dev dependencies to latest versions
    * Updated to async 1.2.1
    * Updated to mongoose 4.0.6
    * Updated to restify 3.0.3
    * Updated to mocha 2.2.5
    * Updated to should 7.0.1
    * Updated to supertest 1.0.1
    * Updated to istanbul 0.3.16

### CODE REVIEW

**Comment by ismarslomic** [comment]
Sorry for breaking build, I will fix this as I didn´t see these failing tests in my local environment before I did a clean npm install. I will commit fixes shortly.

**Comment by MichaelErmer** [comment]
Nice, I was about to commit the exact same stuff, but my test failed and now i found your pull request.

**Comment by ismarslomic** [comment]
Can you please handle this pull request soon?

**Comment by saintedlama** [comment]
Merged, updated packages again (async 1.3.0 works for me) and released package to npm. thx :+1:

**Comment by ismarslomic** [comment]
Cool. Thanks! I see that you are facing issuea with async v1.3.0 as well. I tried debugging, but it was late and I didnt understand all detaila in serve function. It might be easy solution though?

**Comment by saintedlama** [comment]
Travis gave me an error :cry: Currently doing a downgrade, travis test and will release a new package version..

**Comment by ismarslomic** [comment]
You can test locally by downgrading async and making sure to remove async in nodes_modules  folder before `npm install` command. Or you can just use v1.0.0 since I have already done this exercise :)

**Comment by saintedlama** [comment]
0.2.5 released :+1:

**Comment by ismarslomic** [comment]
Why 0.2.5 and not 0.3.0? Are we following semver patterm?

**Comment by ismarslomic** [comment]
See http://semver.org/ .

iven a version number MAJOR.MINOR.PATCH, increment the:

MAJOR version when you make incompatible API changes,
MINOR version when you add functionality in a backwards-compatible manner, and
PATCH version when you make backwards-compatible bug fixes.
Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

**Comment by ismarslomic** [comment]
I would also recommens to release the npm package as version 1.0.0. See also [npm versioning](https://docs.npmjs.com/getting-started/semantic-versioning).

"If a project is going to be shared with others, it should start at 1.0.0, though some projects on npm don't follow this rule"

According to npm there are 92 downloada the last month.

In addition, changelog shouls be moved from README.md to CHANGELOG.md and you should do a github release in parallel with npm release to follow best practices

**Comment by saintedlama** [comment]
Did not see a breaking api change. So I saw no reason for a major version. The 1.0.0 release has to be done - you're right.

**Comment by ismarslomic** [comment]
I agree, no major release in this merge. But minor rather then patch. Agree?

**Pull request merged**
