### PR TITLE
Move changelogs to CHANGELOG.md

### PR DESCRIPTION
**Pull request by ismarslomic**
* Move changelogs to CHANGELOG.md and use file structure such as [angular-material](https://github.com/angular/material/blob/master/CHANGELOG.md) and [angular](https://github.com/angular/angular/blob/master/CHANGELOG.md)
* Add Ismar Slomic to contributors list

### CODE REVIEW

**Comment by saintedlama** [comment]
:+1:

**Comment by saintedlama** [comment]
Pressed the wrong button before

**Comment by saintedlama** [comment]
You're now collaborator :+1:

**Comment by ismarslomic** [comment]
Thanks! :)

**Comment by saintedlama** [comment]
You did a good job with the pull request :dancers:

**Pull request merged**
